linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - bodyclose
    - noctx
    - gosec
    - exhaustive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
  gosec:
    excludes:
      - G104 # unhandled errors on deferred closes

issues:
  exclude-dirs:
    - web
